### ISSUE TITLE
Mockup: My Account

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#15]
The My Account page wasn't originally planned but it seems important to add before the review as it has some important functionality.

- [x] Design 
- [x] Approval

**Comment by Spawbreaker** [comment]
Changed the scope of this page, will be split into four separate issues. This will be the Summary / My Account issue. 

- [ ] As a customer I want to be able to see a summary of info about my account 
- [ ] As a customer I want to be able to log out

**Comment by Spawbreaker** [comment]
![Layout Mockup (6)](https://user-images.githubusercontent.com/37517471/63296780-82176e00-c295-11e9-8d6d-ca46c242f93f.png)

**Comment by pablorich** [comment]
I would just change 'My account' title to 'John Smith's Account' and completely omit the email

**Comment by AnaSandoval-Intersys** [comment]
- The "My billing" and "My shipping" look confusing to me. I was expecting my billing info to be under "My billing" because it gives the impression of it being the title of a section and not a button... To make their purpose clearer I'd suggest to change them for "Edit my billing address" and "Edit my shipping address". Definitely include the word edit.

- For the mobile layout I think the distribution is nice, but for the Desktop and Small Desktop it feels like there's a lot of empty horizontal space on the screen. It feels odd.

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
