### ISSUE TITLE
Mockup: Customer Password Recovery

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_front#16]
- [ ] Design
- [ ] Approval

- [ ] As a customer I want to be able to request a password reset so that I can recover my password if I have forgotten it.
- [ ] As a customer I want to receive an email with information to reset my password after I requested it so that I can change my password.

**Comment by AnaSandoval-Intersys** [comment]
I'd suggest an edit to the stories. The first one should go in the login mockup, since the "forgot my password" request is in there. The password recovery view should be the one we get after the customer has clicked on the link sent to their email. I'm leaving here the mockup for that view. It's the same one as for Admin Password Recovery, since I believe there's nothing to change between the two. 

![Reset Password](https://user-images.githubusercontent.com/53873395/63369572-d712bd00-c345-11e9-97c1-81bbe2efbe86.png)

**Comment by AnaSandoval-Intersys** [comment]
I'm closing issue now, all modifications that should be made according to the feedback given by the product owner will be open as a new issue for clarity of this sprint.
