### ISSUE TITLE
Add color: Other customer Views

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_front#37]
- Cart
- [x] Copy approved layout to Cart
- [x] Add color to components of Cart mockup

- My Account
- [x] Copy approved layout to My Account
- [x] Add color to components of My Account mockup

- Sign Up
- [x] Copy approved upper bar of layout to Sign Up (this view does not include full layout)
- [x] Add color to components of Sign Up mockup

**Comment by roberbnd** [comment]
![Cart](https://user-images.githubusercontent.com/4907027/63905853-307c8b00-c9db-11e9-9aa9-ef51f80e9bd7.png)
![Layout Mockup](https://user-images.githubusercontent.com/4907027/63905866-438f5b00-c9db-11e9-9fd8-b1a6a84688ea.png)

**Comment by Spawbreaker** [comment]
- Cart
  - Added title to all views
  - Unified color
  - Fixed Cart Icon 

On mobile view the Proceed to checkout is fixed on the bottom and the product list can be scrolled down on. Also, the up-down is instead a drop down menu since it's **really** hard to use numeric up-and-down in mobile. 
![Layout Mockup (27)](https://user-images.githubusercontent.com/37517471/63960658-9fe29100-ca54-11e9-9f10-369172399454.png)

**Comment by AnaSandoval-Intersys** [comment]
Closing this issue after new versions of the mockups were approved at the sprint demo
